### ISSUE TITLE
Trained checkpoints & README instructions

### ISSUE THREAD

**Issue by v-i-s-h** [MoayedHajiAli/VidStyleODE-official#2]
Hi,
Thanks for open sourcing the code. Could you please also share the trained checkpoints and update the README on how to use the scripts? I'm trying to run the code, but without instructions, it is getting difficult to debug.

**Comment by MoayedHajiAli** [comment]
Hello @v-i-s-h, 
Apologies for the late reply and for not updating the instructions earlier. I will update the instructions this weekend. As for the pre-trained checkpoints, unfortunately, we will not be able to release them at the moment.

**Comment by 1851759** [comment]
Hi,
Thanks for open sourcing the code. Could you please update the README on how to use the scripts? Thanks a lot.

**Comment by MoayedHajiAli** [comment]
@v-i-s-h @1851759 
I sincerely apologies about the delay in adding the instructions.  I have added the instructions now and tested the code, please let me know if you faced any issues running it. 

To compensate for the delay, I am willing to meet with you and walk you through the code or answer any questions that you may have. To arrange for the meeting, please email me at mh155@rice.edu.

**Comment by 1851759** [comment]
Thanks for updating!I meet some questions in training. The function log_images in src.models.vidstyleode(line 404) needs (B x T x C x H x W) shape of vid_bf,but it gets  (B x C x H x W).SampleT and inversions_bf also lose the dimension T.Could you please help me to solve this question?


vid_bf torch.Size([15, 3, 256, 128])
sampleT (15,)
Summoning checkpoint.
Traceback (most recent call last):
  File "/home/zt/lxp/VidStyleODE-official/main.py", line 764, in <module>
    trainer.fit(model, data.datasets['train'], data.datasets['validation'])
  File "/home/zt/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/zt/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/zt/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/zt/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/home/zt/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "/home/zt/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "/home/zt/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/zt/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/zt/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 410, in _evaluation_step
    call._call_callback_hooks(trainer, hook_name, output, *hook_kwargs.values())
  File "/home/zt/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 208, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/zt/lxp/VidStyleODE-official/main.py", line 506, in on_validation_batch_end
    self.log_img(pl_module, batch, batch_idx, split="val")
  File "/home/zt/lxp/VidStyleODE-official/main.py", line 472, in log_img
    images = pl_module.log_images(batch, split=split)
  File "/home/zt/lxp/VidStyleODE-official/src/models/vidstyleode.py", line 442, in log_images
    ts = ts - ts[0]
IndexError: invalid index to scalar variable.

**Comment by MoayedHajiAli** [comment]
Hello @1851759,
Are you sure you are using the up-to-date version?
It seems that you are have introduced a new line in main.py (line 764) "trainer.fit(model, data.datasets['train'], data.datasets['validation'])"
This line is trying to fit the model on the dataset rather than the data module and thus the batch dimension is missing. Please stick to fitting the model on the data module as in the [provided code](https://github.com/MoayedHajiAli/VidStyleODE-official/blob/905a9c50add03cfa4b3d3db1d4cb0a8ee004ff37/main.py#L749).

**Comment by 1851759** [comment]
I changed "trainer.fit(model, data)" to "trainer.fit(model, data.datasets['train'], data.datasets['validation'])" because it reported errors with logs(`Trainer.fit` stopped: No training batches.).

**Comment by 1851759** [comment]
Could you please help me to solve this question?

84.3 M    Trainable params                                                                                                                                                                
267 M     Non-trainable params                                                                                                                                                            
351 M     Total params
1,407.006 Total estimated model params size (MB)
`Trainer.fit` stopped: No training batches.   
wandb: You can sync this run to the cloud by running:

**Comment by 1851759** [comment]
my base.yml:
project_title: VidStyleODE

model:
  base_learning_rate: 2.0e-6
  target: src.models.vidstyleode.VidStyleODE
  project : "video-manipulation"

  params:
    # frame_log_size : [256, 192] 
    frame_log_size : [256, 128] 
    content_mode : "mean_inversion"
    video_length : 50 # estimate number of frames per video
    sampling_type : "static" # static, interpolate, or extrapolate. Interpolate masks intermediate frames while training, and extrapolate masks last few frames.
    n_sampled_frames : 4 # number of frames to sample for backpropagation at each training step, reduce for a smaller memory contraints

    delta_inversion_weight : 0.01
    l2_latent_eps : 0.02
    lambda_vgg: 10.0
    l2_latent_lambda : 1.0
    manipulation_strength : 2

    clip_loss_lambda:
      target: src.modules.schedulers.LambdaScheduler
      params:
        warm_up_steps: 5000
        lr_min: 0.01
        lr_max: 2.5
        max_decay_steps: 200000

    consistency_lambda:
      target: src.modules.schedulers.LambdaScheduler
      params:
        warm_up_steps: 0
        lr_min: 0.01
        lr_max: 1.0
        max_decay_steps: 40000

    rec_loss_lambda: # used in a small scale for fine-grained details toward the end of the training
      target: src.modules.schedulers.LambdaScheduler
      params:
        warm_up_steps: 50000
        lr_min: 0.01
        lr_max: 0.1
        max_decay_steps: 100000


    perceptual_loss_config:
      target: src.losses.splice_vit.SpliceLoss
      params:
        structure_lambda : 0.8
        cls_layer_num : 8


    modulation_network_config:
      target: src.modules.minigpt.CrossAttentionModulation
      params:
        shared_attn_params : False
        out_dim : 512
        n_embd : 512 # input dim
        n_layer : 8
        content_block_size : 1
        dyn_attn_n_layer : 6
        dyn_block_size : 48 # >= (img_size[0] // 2 ^ netE_num_downsampling_sp) * (img_size[1] // 2 ^ netE_num_downsampling_sp)
        n_head : 8

    video_ecnoder_config:
      target: src.modules.video_encoder.VideoEncoderWLatentODE
      params:
        # img_size : [128, 96] 
        img_size : [128, 64] 
        dynamic_latent_out_dim : 512 # must match ODE_func_config latent_dim
        spatial_code_ch : 256 # hidden dim
        netE_num_downsampling_sp : 4

    stylegan_gen_config:
      # target: src.modules.stylegan_wraper.StyleGAN2Generator
      target: src.modules.stylegan_wraper.StyleGAN2Fashion
      params:
        pkl_file: pretrained_models/stylegan_human_v2_1024.pkl


    style_mapper_config:
      target: src.modules.mapper.AttentionAttributeMapper # TripleAttributeMapper
      params:
        predict_delta: True
        use_coarse_mapper: [True, False, False] # Since the coarse mapper only handles pose, we don't want to do any modulation
        use_medium_mapper: [True, False, False]
        use_fine_mapper: [True, False, False]
        coarse_cut_flag: False
        medium_cut_flag: False
        fine_cut_flag: False
        mod_shape : [[1, 4, 1], [1, 4, 1], [1, 10, 1]]
        num_of_layers : [7, 5, 5]
        attr_vec_dims: [512, 0, 0] #much match W_cont + CLIP embedding



data:
  target: main.DataModuleFromConfig
  params:
    batch_size: &bs 8 # MUST Match batch size in dataset
    # batch_size: 16 # MUST Match batch size in dataset
    num_workers: 8
    train:
      target: src.data.dataset.ImageCaptionFolderDataset # Changed from data.video.ImageCaptionFolderDataset to data.dataset.ImageCaptionFolderDataset
      params:
        video_list: data/xxx/train.txt
        img_root:  /xxx/train/img
        inversion_root: /xxx/train/pti
        inverted_img_root : null # optional, add if you want to log the frame-by-frame inverted video
        # skip_frames : 5
        skip_frames : 0
        n_sampled_frames : 8
        irregular_sampling : True
        batch_size : *bs # MUST match the loader batch size
        # batch_size : 16 # MUST match the loader batch size
        # size : [256, 192]
        size : [256, 128]
        # attribute : "Sleeves"
        # attribute_stats : 'data/fashion/attributes_stats.yaml'

    validation:
      target: src.data.dataset.ImageCaptionFolderDataset # Changed from data.video.ImageCaptionFolderDataset to data.dataset.ImageCaptionFolderDataset
      params:
        video_list: data/xxx/test.txt
        img_root:  /xxx/test/img
        inversion_root: /xxx/test/pti
        inverted_img_root : null # optional, add if you want to log the frame-by-frame inverted video
        # skip_frames : 5
        skip_frames : 0
        n_sampled_frames : 15
        irregular_sampling : False
        batch_size : *bs # MUST match the loader batch size
        # batch_size : 16 # MUST match the loader batch size
        # size : [256, 192]
        size : [256, 128]
        # attribute : "Sleeves"
        # attribute_stats : 'data/fashion/attributes_stats.yaml'


lightning:
  trainer:
    limit_val_batches : 2 # logging gifs is expensice

**Comment by v-i-s-h** [comment]
@MoayedHajiAli Thanks a lot for updating the repo. I will go through this and surely get back to you if I have any doubts. Thanks for offering such wonderful support!

**Comment by 1851759** [comment]
> Could you please help me to solve this question?
> 
> 84.3 M Trainable params 267 M Non-trainable params 351 M Total params 1,407.006 Total estimated model params size (MB) `Trainer.fit` stopped: No training batches. wandb: You can sync this run to the cloud by running:

I solve it by making the batch size smaller than the number of videos.

**Comment by MoayedHajiAli** [comment]
@1851759 I am glad that you could solve it. 
Yes, in our code repo we drop the last batch in the dataloader, therefore if you do not have enough number of videos for even a single batch you will get this message.
Please let me know if you faced any other issues.

**Comment by 1851759** [comment]
When I use "resume", it reports the error
```
Traceback (most recent call last):                                                                                                                                                        
  File "/xxx/VidStyleODE-official/main.py", line 794, in <module>                                                                                                                 
    trainer = Trainer(**vars(trainer_opt), **trainer_kwargs, resume_from_checkpoint=ckpt)                                                                                                 
  File "/xxx/miniconda3/envs/vidstyleode/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: Trainer.__init__() got an unexpected keyword argument 'resume_from_checkpoint'
```
I read the doc of pytorch_lightning 2.2.1.There is no argument 'resume_from_checkpoint' in Trainer.__init__().

```
Trainer.fit(model, train_dataloaders=None, val_dataloaders=None, datamodule=None, ckpt_path=None)

Parameters:
xxx

ckpt_path – Path/URL of the checkpoint from which training is resumed. Could also be one of two special keywords "last" and "hpc". If there is no checkpoint file at the path, an exception is raised.
```

Do I need to change "trainer.fit(model, data)" to "trainer.fit(model, data, ckpt_path=opt.ckpt)" if using opt.resume？

**Comment by MoayedHajiAli** [comment]
Hello @1851759, 
Yes. Since I have updated the code to a newer pytorch lightning version, there is some legacy code. I only tested the main functionality of training with the new pytorch lightning. 
Now, I have updated the repo with the correct resume (i.e using  passing the checkpoint to the fit function) and added instruction in the README about how to resume.
